# Site wide configuration

title:            Site Title
locale:           en_US
logo:             # filename of a logo image that has been placed into your images directory
# If using a Github User page (i.e. username.github.io) to host your site, delete the default url that is below.
 url: ./jekyll-workshop
# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Your Name
  avatar: bio-photo.jpg
  bio: "A brief description of yourself."
  email: #emailaddress
  twitter: #username
  facebook: #username
  instagram: #username
  linkedin: #username
  github: #username
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  bing-verify:
  stackoverflow: #123456/username from a "http://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
